---
title: "Ski Pass Exploratory"
author: "Winston Saunders"
date: "March 26, 2015"
output: html_document
---


```{r}
        ## PASS NUMBER
        Pass <- "MBA6360970"

        Directory <- "/Users/winstonsaunders/Documents/Ski_Data2/"
        
        ski_runs<-read.csv(paste0(Directory,Pass,".csv"))


```

```{r}

        head(ski_runs)

        ski_runs$time<-strptime(ski_runs$time, "%Y-%m-%d")

        str(ski_runs)

        head(ski_runs, 20)

```

Let's 

```{r}
library(timeDate)

ski_runs$weekend<-isWeekend(ski_runs$time)
ski_runs$holiday<-isHoliday(as.character(ski_runs$time))
ski_runs$bizday<-isBizday(ski_runs$time)
```

```{r}

stock.data <- transform(stock.data,
                        week = as.POSIXlt(Date)$yday %/% 7 + 1,
                        wday = as.POSIXlt(Date)$wday,
                        year = as.POSIXlt(Date)$year + 1900)

library(ggplot2)
p1<-ggplot(stock.data, aes(week, wday, fill = Adj.Close)) + 
  geom_tile(colour = "white") +
  scale_fill_gradientn(colours = c("lightblue", "blue", "darkblue", "darkgreen")) + 
  facet_wrap(~ year, ncol = 1)

print(p1)